# Generated by Django 4.2.7 on 2023-11-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_users_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
