name: Deploy

on: 
  push:
    branches:
    - main
      
jobs:
  build:
    runs-on: debian-11
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.2]
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 34.125.13.218
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/mr_kanat2004/helloWorld
          source /home/mr_kanat2004/venv/bin/activate
          git pull
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
